services:
  jw-media-download:
    build: .
    #image: drumsergio/jw-media-download:0.0.1
    volumes:
      - /mnt/d/jworg:/jworg:rw
    dns:
      - 8.8.8.8
      - 1.1.1.1
    privileged: true
    environment:
      - JW_LANG=S
      - JW_OUTPUT_PATH=/jworg