services:
  jw-media-download-publications:
    build:
      context: .
      dockerfile: Dockerfile-publications
    #image: drumsergio/jw-media-download:0.0.1
    volumes:
      - E:\jworg:/jworg:rw
    privileged: true
    environment:
      - JW_LANG=S
      - JW_OUTPUT_PATH=/jworg/jwpubs

  # jw-media-download-media:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-media
  #   #image: drumsergio/jw-media-download:0.0.1
  #   volumes:
  #     - E:\jworg:/jworg:rw
  #   privileged: true
  #   environment:
  #     - JW_LANG=S
  #     - JW_OUTPUT_PATH=/jworg/vtts